apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/TechTalk-With-Nathan/gitops-argocd-vault.git
    targetRevision: main
    path: apps/issuer
    kustomize: {} 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
